# Generated by Django 5.2.4 on 2025-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_data_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='ekyc_apical_api_key_fed7af_idx')],
            },
        ),
    ]
