# Generated by Django 5.2.4 on 2025-07-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
